### PR TITLE
Update to version 0.4.2

### LINKED ISSUE #4: v0.4.2 missing
The updater bot fails due to missing sources on pypi.
Reported to author in https://github.com/DaanVanVugt/h5pickle/issues/13

### PR DESCRIPTION
**Pull request by Anthchirp**
and fix missing maintainer

resolves #4 and closes #5

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Anthchirp** [comment]
@DaanVanVugt Am I right in assuming that your github account was previously under the name of Exteris, and that you want to continue maintaining this package?

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by DaanVanVugt** [comment]
Yes, that is correct!

Daan

Op di 13 okt. 2020 22:03 schreef Markus Gerstel <notifications@github.com>:

**Comment by Anthchirp** [comment]
@conda-forge-admin, please rerender

**Comment by Anthchirp** [comment]
If you're happy with me staying on then this is ready to be merged.

**Comment by DaanVanVugt** [comment]
Thanks @Anthchirp

**Pull request merged**
